### ISSUE TITLE
Separate Quantum page into 32-bit & 64-bit

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/firefox-health-dashboard#11]
specifically around ongoing quantum efforts, since they have different priorities/scopes/needs 32 and 64 bit should be shown independently

**Comment by armenzg** [comment]
@stuartphilp I've decided that doing this split now will be cleaner.
Would you mind telling me what to keep for the 32-bit page?
Thanks.

**Comment by armenzg** [comment]
Some graphs like Photon perf are "any OS & any architecture".

The Hassal graph, the first paint and hero element contain data up to September of last year (data from the spreadsheet). Should this *only* belong to the 64-bit page? Also, is the data going to be updated?

**Comment by armenzg** [comment]
I'm considering closing this since the Speedometer graphs are the only ones I can think of that have 32-bit/64-bit split.
In my recent work around speedometer I'm reducing the number of speedometer graphs and grouping per architecture. Thus, making it easier to distinguish each.

**Comment by armenzg** [comment]
Closing as this improved page makes the separation between 32-bit and 64-bit less painful.
https://platform-health-pr-52.herokuapp.com/quantum
![image](https://user-images.githubusercontent.com/44410/36693892-9cb308b6-1b0a-11e8-9c37-b7f28646b499.png)

**Comment by armenzg** [comment]
I noticed that all the Talos graphs also contain win7-32/win10-64 data.
Tp6 would benefit the most of a split up since it tracks so many pages rather than just one value.
