### ISSUE TITLE
Usability improvements for Android V2 view

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#122]
There are just too many graphs.
Here's a draft of the next pass for it.
![image](https://user-images.githubusercontent.com/44410/42733516-738b857c-8800-11e8-9f4b-235700bdac77.png)

I should have a PR for this (or close to it) in this coming week.

**Comment by cpeterso** [comment]
There definitely are a lot of graphs! :) What if graphs were shrunk down and displayed in a grid so that they all fit on one screen? Each graph has a lot of empty space. The graphs' trends would still be visible on a small graph and the trends (and whether WebView or GeckoView is faster on each site) are more important than the tiny ups and downs each day.

**Comment by armenzg** [comment]
After speaking with @wlach and @cpeterso I've come up with this second draft.
This is based on inspiration from [mission-control](https://data-missioncontrol.dev.mozaws.net/#/release/windows).
For now, I will be focusing on the backend issue I've reported and I will then come back to this.
I expect 2-4 days to complete this.
I will probably tackle it early next week.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/44410/42782929-5bf06266-8918-11e8-9e9f-8f85def6a184.png">

**Comment by wlach** [comment]
I think this is great. The only thing I'd add is some kind of header element at the top saying what the current overall score is. i.e.:

<center><h1>33 out of 50 in target range</h1></center>

**Comment by cpeterso** [comment]
The dashboard's most important use case is to see all the graphs on one page so a human can quickly check all the graphs (even if that page needs to scroll like it does today). We have that today. 😃 Visually comparing graphs for two different sites side-by-side (like abcnews.go.com versus m.spiegel.de is the first screenshot above), however, is a low priority because the sites have are loading different content and thus their results are not related.

I think a more useful UI change (and much less work) would be to add link anchors to the long page's graphs so people can share deep links directly to a particular site's graph.

**Comment by wlach** [comment]
Asking a human to manually scroll through 100 graphs and checking that each one is within a range seems rather time consuming and error prone to me, which is why I suggested some kind of tabular summary.

**Comment by cpeterso** [comment]
I see what you mean. A tabular summary that can a human can quickly scan sounds useful.

**Comment by cpeterso** [comment]
@canuckistani suggests the page show a red/yellow/green summary table showing just the number of sites that:

* GeckoView > 20% slower than WebView (red)
* GeckoView > 0% and <= 20% slower than WebView (yellow)
* GeckoView <= 0% (i.e. faster than) WebView (green)

https://gist.github.com/canuckistani/8d5a240056047cee0ccab01ece538afa

**Comment by cpeterso** [comment]
@canuckistani suggests the page show a red/yellow/green summary table showing just the number of sites that:

* GeckoView > 20% slower than WebView (red)
* GeckoView > 0% and <= 20% slower than WebView (yellow)
* GeckoView <= 0% (i.e. faster than) WebView (green)

Even if just in a console table:
https://gist.github.com/canuckistani/8d5a240056047cee0ccab01ece538afa

**Comment by cpeterso** [comment]
>> GeckoView ... slower than Target (yellow)
> the target being WebView + 20%.
> The page currently turns a site red if it is +100% of the target.

I see. That sounds good now that I understand. Being faster than our target (WebView + 20%) is worthy of being green. :)

**Comment by armenzg** [comment]
Does this work?

![image](https://user-images.githubusercontent.com/44410/42954083-d3b60c32-8b49-11e8-9475-20d3b06739d8.png)

**Comment by andreasbovens** [comment]
That looks good to me. What will the detailed view look like?

**Comment by cpeterso** [comment]
Looks good!

**Comment by armenzg** [comment]
I currently have this:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/44410/42969543-7e0206e4-8b74-11e8-9513-a5e135cebfe0.png">

**Comment by armenzg** [comment]
I won't be able to finish today.
It needs real data for the **overall summary** (the sites are using real data) and some CSS grid love.

However, here's what I currently have:
* [Overall view](https://platform-health-pr-129.herokuapp.com/android)[1]
* [Site drill down](https://platform-health-pr-129.herokuapp.com/android/graph?site=marvel.wikia.com/wiki)[2]

Todo:
* Calculate real data for overall summary
* Fix grids
* Long websites should only show domain
  * NOTE: There can be two sites for the same domain; differentiate them

[1]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/44410/43023056-7ccda026-8c37-11e8-9b93-12e7e88d120a.png">
[2]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/44410/43023066-87ca3516-8c37-11e8-9fe2-339fe3d01c84.png">

**Comment by vickychin** [comment]
Would it be possible when I click on the red summary bar at the top that it'd just give me the two graphs that are in the red zone? Same as yellow? That would be super helpful.

**Comment by armenzg** [comment]
@vickychin Unfortunately, I'm too tight for time. If something is *not* a blocker I will be pushing it to the end of August.

TODO:
* Determine issue loading flipkart.com
* Calculate real data for overall summary
* Change look of overall summary to match designed draft
* Long websites should only show domain
  * NOTE: There can be two sites for the same domain; differentiate them


This is what my next code push looks like ([live link](https://platform-health-pr-129.herokuapp.com/android)):
<img width="875" alt="image" src="https://user-images.githubusercontent.com/44410/43092223-74ee3bc8-8e7a-11e8-938a-95c21c110ea1.png">

**Comment by armenzg** [comment]
Latest look:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/44410/43101205-c4e52b26-8e95-11e8-8a4f-9f6cfc0c5b5f.png">

**Comment by armenzg** [comment]
I've tackled all my TODOs. There might be some minor tweaks coming, however, nothing that I will need you to check.

@vickychin @cpeterso @andreasbovens @npark-mozilla: Could you please test the current deployment? I'm looking for _blockers_. If wlach doesn't see any issues I will land it.

* [Link](https://platform-health-pr-129.herokuapp.com/android)
* [Drill down of a site](https://platform-health-pr-129.herokuapp.com/android/graph?site=flipkart.com/search?q=moto%20g5%20plus&sid=tyy)

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/44410/43159194-a97e355c-8f4f-11e8-8656-c5d0df88163a.png">

**Comment by armenzg** [comment]
After minor tweaks; time to request review:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/44410/43163138-2c8ca1a8-8f5b-11e8-83d7-fa7fdf432cb2.png">

**Comment by cpeterso** [comment]
👍  The site on the staging server looks good! I like the top summary of how many sites are red/yellow/green and the % from target in the site list. I tested some links and graphs and didn't find any problems.

**Comment by vickychin** [comment]
Previously we had the target to be GeckoView <= WebView + 20%
Anything that met the target was green, red was anything that was 100% worse than webview, and yellow was in between those two. Seems like the definition has changed?

I am ok with the new colouring also, I just want to point out we're changing the target and colour definitions. @cpeterso @andreasbovens

**Comment by vickychin** [comment]
Actually the target in the graphs is still the same as before, the colouring changed. 

Like the new layout and format on the staging server! Thanks @armenzg

**Comment by armenzg** [comment]
@vickychin we changed the criteria in https://github.com/mozilla/firefox-health-dashboard/issues/122#issuecomment-406005811

I've pushed one more change to fix an issue with the regex.
It now matches all 76 URLs instead of 66.

If there's anyone in here good with regexes, would you mind looking at [this](https://regexr.com/3svms)? I can't figure out how to get rid of the "/" at the end of some URLs.

**Comment by armenzg** [comment]
@wlach hahaha totally baited you! 😄 Next time I see you I will want to understand that question mark within the grouping!

I've pushed a modified version of your regex.

**Comment by armenzg** [comment]
@andreasbovens I will add it once I tackle the review feedback from wlach.

**Comment by armenzg** [comment]
I've landed the PR. It is live now.

Thank you all for participating on this PR.
Special thanks to @wlach for all his design experience and code review feedback!

The last screenshot:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/44410/43318819-5b07c884-9170-11e8-8787-3630ff24c1ef.png">
