### ISSUE TITLE
Generate source maps for production

### ISSUE THREAD

**Issue by digitarald** [mozilla/firefox-health-dashboard#38]
Just a nice to have to understand and debug health.graphics life; making it more educational.

**Comment by eliperelman** [comment]
Should be able to add a line here https://github.com/mozilla/firefox-health-dashboard/blob/master/.neutrinorc.js#L132 with:

```js
neutrino.config.when(process.env.NODE_ENV === 'production', config => {
  config.devtool('source-map');
});
```

**Comment by armenzg** [comment]
This seemed to work on production.
I've merged it and it should be live soon.
