### ISSUE TITLE
Speedometer percentage changes should include positive/negative symbol

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#40]
Right now, the percentage value is *always* positive regardless if we're slower.

**Comment by csd713** [comment]
hello @armenzg I would like to take this up. Could you please help me?

**Comment by armenzg** [comment]
@csd713 sure!
Could you please let me know when you have the project running locally?
On the quantum page you should see this:
![image](https://user-images.githubusercontent.com/44410/36865239-e9a30f50-1d5c-11e8-976d-eec28d612e60.png)

The percentage value should have a minus in front of the two digits.

**Comment by csd713** [comment]
@armenzg my project is up and running locally.
Here is my solution:

Instead of `(1 - ratio) * 100)` for 'reading' variable, we have to change it to `(ratio - 1) * 100)`.
It results in correct value and also correct symbol (positive/negative).
file to change: speedometer.js

Please let me know if I'm missing something.

**Comment by armenzg** [comment]
When referring to code please insert links to it. It makes conversations easier.
For instance:
https://github.com/mozilla/firefox-health-dashboard/blob/master/src/components/awfy/speedometer.js#L90

In any case, I believe that should do it. Do you want to get a PR going?

**Comment by csd713** [comment]
Thanks for the advice. I'll use links next time.

Yes, i'll send a PR. Is there any document that I have go through to understand the process before sending a PR?

**Comment by armenzg** [comment]
I wrote this for another project I wrote; does it help? https://github.com/mozilla/firefox-code-coverage-frontend/blob/master/CONTRIBUTING.md
