### ISSUE TITLE
The status widget highlight looks awkward

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#45]
We should *only* have white background behind the targetStatus and not see the green/yello at the top.

![image](https://user-images.githubusercontent.com/44410/36433367-539bc030-162a-11e8-9f96-79c7daa12d42.png)

**Comment by csd713** [comment]
Hi @armenzg I would like to take this up. How can reproduce this issue?

**Comment by armenzg** [comment]
Hi @csd713 you will have to load this page locally
http://localhost:5000/quantum and resize the window until you see the issue happening.

Unfortunately, the speedometers graphs (section "#1 - Speedometer") are not working correctly, thus, we can't reproduce the issue I reported 13 days ago.
There's an issue on the downstream service. I'm going to remove those graphs.

There's a similar issue for one of the graphs below when text is long (see green area on 2nd graph; the smiley face is being hidden):
![image](https://user-images.githubusercontent.com/44410/36991476-c4c39d3c-2075-11e8-80ed-2fe87a5eeb88.png)

Since the original issue cannot be reproduced anymore we could close the issue if you like since the new issue is not as noticeable.

Please let me know what you prefer. I'm happy either way.

**Comment by csd713** [comment]
Hello @armenzg I was able to reproduce this issue on a bigger screen (15 inch MBP).
I tried to wrap the background-color for the text, but I couldn't find a solution. I would really appreciate if could you help me with any pointer to achieve it.

**Comment by armenzg** [comment]
Hi @csd713 I'm not very good at CSS so I will share some of what I discovered and hopefully that will trigger ideas to try. This is not a very important issue in case you end up deciding not to spend more time on it. It might be a good learning opportunity but don't worry too much if you decide to give up.

I used the dev tools inspector to look at the <header>, <h3> and <aside> elements.
If we disable (you can disable directly in the devtools and see the changes live) the "overflow" value:
https://github.com/mozilla/firefox-health-dashboard/blob/master/src/index.css#L255
I get this:
https://cl.ly/0L0B093c341j

If you select the <header> elemnt and check at the CSS rules for it you will notice that there are two background-colour properties applied to it (gray and green background).
If we add background-color *only* to the <h3> element we get this:
https://cl.ly/2L1Z1w311L2A

I think there might be two ways here:
* Make those CSS changes
* Modify the smiley png to have transparency outside of the face (leave the teeth white)

The 2nd one might be the nicest approach (and what I would prefer) but it's been almost two decades since the last time I deal with png files and I won't be able to help too much.

There's also another CSS change that would make the smiley face hover at the center heght:
* Change .criteria-widget header's 'align-items' to 'center'

This shows it with that change:
https://cl.ly/0j3a1S2m2e1t

**Comment by armenzg** [comment]
This will get fixed on #43
