### ISSUE TITLE
Quantum page polishing

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#53]
After speaking with @stuartphilp we need to address the following:

- [x] Drop "First Paint" and "Hero Element"
- [x] Remove incorrect labels for tp6 loaded

Speedometer changes:
- [ ] Comparing against Canary 2017 should be 105% target rather than 95%
- [ ] Add permanent legend labels
- [ ] 1st graph to say "Nightly, Beta & current Canary"
- [ ] 2nd graph to say "Current Nightly vs Canary Dec. 2017"

**Comment by csd713** [comment]
hi @armenzg I would like to work on this issue. Could you please help me with more details on each item listed above.

**Comment by armenzg** [comment]
Hi @csd713 , have a close look at [this page](https://health.graphics/quantum) and compare it to what I wrote down. 

With regards to the labels, removing the "win7-32" and "win10-64" would be sufficient.

**Comment by armenzg** [comment]
Hi @csd713 I have someone I'm on-ramping on this project and this would be a great issue to start with. If you can have a fix in the next couple of days that would be great, otherwise, I would like to re-assing it.

If there are no other issues in this repo that feel comfortable tackling I have a bunch of issues in this other repo:
https://github.com/mozilla/firefox-code-coverage-frontend/issues

**Comment by csd713** [comment]
Hi @armenzg It might be a while for me to have a look at this, so please reassign it. I will look into issues in new project

**Comment by armenzg** [comment]
Thanks @csd713 for your understanding! I hope everything is well with you.

**Comment by sarah-clements** [comment]
This issue was incorporated into another issue and resolved with #80
