### ISSUE TITLE
Update all Talos perfherder signatures

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#68]
We renamed a bunch of Talos jobs to include "stylo" in their name (I think) back in February.
Unfortunately, if you look at the Quantum page you would not notice easily that we're missing data since then.

**Comment by armenzg** [comment]
@jmaher @stuartphilp I would like your feedback on this.
I have left the "old" isgnatures in order to allow comparing the new signatures more easily.

Please visit https://platform-health-pr-74.herokuapp.com/quantum

Here's some things I've noticed:
* Talos TP6: Loaded
  * There is some weirdness on Perfherder
  * @wlach could you please look at this screenshot? [1]
* The moonshot regression can easily be noticed at the end of February
* The plotting on fx-health can **sometimes** make it look like there are new baselines [2]
   * Visiting the links on Perfherder shows that there could be something to it

I've also pushed a temporary commit that will soon be deployed where each graph will be shown on their own row to help seeing the graphs a bit bigger.

[1]
![image](https://user-images.githubusercontent.com/44410/37670836-b2e7a046-2c40-11e8-988b-1014bf66e5b9.png)

[2]
![image](https://user-images.githubusercontent.com/44410/37671740-cd6b9eca-2c42-11e8-9976-78c5183feeb0.png)

[3]
https://treeherder.mozilla.org/perf.html#/graphs?timerange=5184000&series=mozilla-central,1538634,1,1&series=mozilla-central,1316966,1,1&series=mozilla-central,1503232,1,1&series=mozilla-central,1538865,1,1
![image](https://user-images.githubusercontent.com/44410/37671844-0023b7e4-2c43-11e8-9cf6-bdddd09cd3eb.png)

**Comment by jmaher** [comment]
tp6 was off for ~2 weeks as we had difficulties getting it running on the
moonshots and had it off and it was overlooked in backing out when we
rolled back to the old IX hardware.

**Comment by armenzg** [comment]
I've got feedback from Stuart via IRC.
I've merged this.

I know the Perfherder graphs now look cluttered, however, we will get in a better shape when we separate 32-bit and 64-bit into their own pages (See issue #11 )
