### ISSUE TITLE
Certain Quantum routes not rendering

### ISSUE THREAD

**Issue by sarah-clements** [mozilla/firefox-health-dashboard#81]
Several routes in /src/quantum/routes.jsx are failing when testing on health.graphics and locally:
- 'track' route shows in error in the console (TypeError: e is undefined) and the page isn't loading
- 'responsiveness/parent', 'responsiveness/content', and 'pageload/render' all fail to fully load and show this message in the console: 
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://firefox-health-backend.herokuapp.com/api/perf/version-evolutions?child=content&e10sEnabled=true&metric=TIME_TO_NON_BLANK_PAINT_MS&os=Windows_NT. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)"

**Comment by sarah-clements** [comment]
It might be a result of this: https://github.com/koajs/cors/issues/18

**Comment by sarah-clements** [comment]
It doesn't look like the koa-cors library is being maintained; switching to the [@koa/cors](https://github.com/koajs/cors) library eliminated the CORS console message, however, it looks like the problem might be that for some of the routes the telemtry.aggregates API is returning a 500.

**Comment by sarah-clements** [comment]
I've done research on the backend and the 'responsiveness/parent', 'responsiveness/content', and 'pageload/render' 500's are all due to a failure in the Telemetry.getEvolutions function in the evolution-versions API (the first two due to dates not being available for Aurora v61) and for the latter I'm still researching as to whether the query param metric has changed or is not available for specific versions. I'll be opening a pr in the firefox-health-backend when I know more.

**Comment by sarah-clements** [comment]
Update: no change is needed for aurora to beta merge, but @stuartphilp will look into the metric change. Other issues were fixed with [this](https://github.com/mozilla/firefox-health-backend/pull/22) backend pr  (except for the CORS issue).

**Comment by stuartphilp** [comment]
@sarah-clements suggestion was to use the "no_netopt" probe for now as it will be the closest to the old probe data (the network optimizations are new and a subset of old data, so it won't be 100% comparable)

**Comment by sarah-clements** [comment]
All remaining issues have been fixed (except for CORS as Armen might want to look into different library options himself).
