### ISSUE TITLE
Devtools dashboard

### ISSUE THREAD

**Issue by digitarald** [mozilla/firefox-health-dashboard#9]
### Operations

- P1/P2 Burn up charts
- Triage backlog
- Bug age

### Performance

- DAMP breakdown: https://bugzilla.mozilla.org/show_bug.cgi?id=1397745

### Engagement

- Opening counts (per channel)

**Comment by digitarald** [comment]
Data sources:

BHR: https://analysis-output.telemetry.mozilla.org/bhr/data/hang_aggregates/historical_data.json?d=1028
Talos: https://github.com/devtools-html/performance-dashboard/blob/master/perfherder/perfherder-signatures.js

**Comment by armenzg** [comment]
I believe this is completed.
Please correct me if I got it wrong!
