### ISSUE TITLE
Add a first-blank-paint Photon perf graph

### ISSUE THREAD

**Issue by past** [mozilla/firefox-health-dashboard#99]
In 61 we [added](https://bugzilla.mozilla.org/show_bug.cgi?id=1453782) a new perf measurement for the early blank window paint that has yet to ship to our release population. You can see it as the last graph in my dashboard:

https://astithas.com/perm/photon-perf/

It would be good to add this to the main Quantum dashboards as well.

**Comment by armenzg** [comment]
I will look into this tomorrow

**Comment by armenzg** [comment]
@past Could you please give me your feedback?
https://platform-health-pr-102.herokuapp.com/quantum/64

Clicking on the header of the graph will take you here:
https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=median&arch=x86-64&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F62&measure=SIMPLE_MEASURES_BLANKWINDOWSHOWN&min_channel_version=nightly%252F59&processType=*&product=Firefox&sanitize=0&sort_keys=submissions&start_date=null&trim=0&use_submission_date=0

![image](https://user-images.githubusercontent.com/44410/41161941-5eae083e-6b02-11e8-8a31-5c6d3e8b9e9c.png)

**Comment by past** [comment]
Looks great! The only odd thing is that it doesn't seem to be filtering for parent process only (same as First Paint), which is what these measurements are really about. Not a big deal though if it's too cumbersome to fix.

**Comment by armenzg** [comment]
What would a fix look like? I don't quite understand.
What would a correct fetch to Telemetry look like?

**Comment by past** [comment]
You could [pass](https://telemetry.mozilla.org/new-pipeline/evo.html#!max_channel_version=nightly%252F62&min_channel_version=nightly%252F60&sanitize=1&trim=1&use_submission_date=0&measure=SIMPLE_MEASURES_BLANKWINDOWSHOWN&product=Firefox&processType=parent) the `processType=parent` query argument or add it as a [filter](https://github.com/past/past.github.com/blob/master/perm/photon-perf/js/index.js#L70) if you are using TelemetryWrapper.

**Comment by armenzg** [comment]
That filter is defined on the backend:
https://github.com/mozilla/firefox-health-backend/blob/photon/src/perf/telemetry_config.js#L41

I think there might be a bug on the frontend where the link is built incorrectly.
If I put your graph and the one produced in my PR I can see that they're plotting the same data (see screenshot).

I will land the code once I get my approval and see how we can fix the discrepancy on a follow up.
﻿
<img width="706" alt="screenshot 2018-06-11 10 04 57" src="https://user-images.githubusercontent.com/44410/41315842-8dbd4946-6e45-11e8-9657-8144c08bd00a.png">

**Comment by armenzg** [comment]
Discrepancy filed:
https://github.com/mozilla/firefox-health-dashboard/issues/103

**Comment by armenzg** [comment]
This is done.
